### ISSUE TITLE
需要测例

### ISSUE THREAD

**Issue by JianxinMa** [a1exwang/alex2v9#1]
需要你们写几个小测例，比如输出hello world之类的（我不知道你们写asm的格式，不知道怎么输出）。

然后顺手帮忙：
1. 编译下；
2. 转成v9的格式；
3. 给出调试信息。

我记得之前试的时候你们的2、3步给出的并不完全符合我这边的要求。
所以你们先贴出来2、3的结果，我再指出哪里格式不对（格式见 https://github.com/JianxinMa/v9.js/blob/gh-pages/doc/debugger.md 的 Support from the Compiler）。

（我的linux被我乱弄弄崩到启动不能了....真是耽误时间哎）

**Comment by JianxinMa** [comment]
注：我在v9的类elf文件的.text开头有插入东西。

**Comment by a1exwang** [comment]
a.v9是可执行程序
a.v9.sym是符号
src和asm文件夹是源码, 由于编译是指定了-l选项, 所以include的头文件都是源码目录下的, 没有linux的头文件.

[alexv9.zip](https://github.com/a1exwang/alex2v9/files/300354/alexv9.zip)

**Comment by a1exwang** [comment]
请问在你文档中的这个部分.
"""
Store the source file name right after the above magic number. For example, save root/etc/os.c after 0xFF2017FF. It should be terminated by '\0'.
"""
root/etc/os.c是源码文件吗? 如果有多个源码文件怎么办

**Comment by JianxinMa** [comment]
debugger.md给的例子里：
1. debug信息文件的第一行是 “= root/etc/os.c”，
2. 而elf的text处插入的字符串是“root/etc/os.c”

实际上，只要这两个保持一样即可，建议用含main的那个c文件的名字。

**Comment by a1exwang** [comment]
请问0xFF2017FF是big endian还是little endian, text段插入字符串用utf8编码格式是否可以?

**Comment by a1exwang** [comment]
请问如果在text段前面添加一段数据的话, 那么文件头的entrypoint是指向text段前面添加的数据还是本来的入口?

**Comment by a1exwang** [comment]
[alexv9.zip](https://github.com/a1exwang/alex2v9/files/303914/alexv9.zip)

**Comment by JianxinMa** [comment]
little endian 字符串应该只有英文，用ASCII即可（UTF8的英文部分和ASCII是一样的）。

是在.text起始“处”而不是.text“前”插入，相当于.text的大小变大了，但.text起始地址还是那个，倒是.data和.bss的起始地址后移了。

**Comment by JianxinMa** [comment]
entrypoint自然也就后移了，因为它在.text中的位置后移了

**Comment by a1exwang** [comment]
因为我们是通过elf文件来生成v9 executable的, 而不是链接器直接生成v9 excutable
所以如果整个text段都平移的话代码中的所有地址都会无效, 所以只能在text之前加...

**Comment by a1exwang** [comment]
文件名的问题的确是我疏忽抱歉..
 text段首插入的也问题解决了
[alexv9.zip](https://github.com/a1exwang/alex2v9/files/304118/alexv9.zip)
