### ISSUE TITLE
sym文件里变量位置的偏移值似乎有误

### ISSUE THREAD

**Issue by JianxinMa** [a1exwang/alex2v9#4]
看这个片段：

```
g uint32_v data +13000 (uint)
g int32_v data +13004 (int)
g char_v data +13008 (char)
g uint8_v data +13009 (uchar)
g int32_ptr data +1300 (ptr(int))
g arr data +13010 (array(100|4(ptr(ptr(ptr(char))))))
...
.data 0x13000
.bss 0x13010
```

注意到几个问题:
1. arr是在bss段，不是data段；
2. 我用的是相对bss或data起始地址的偏移值，而不是绝对地址；
3. 偏移值是十进制的（没有0x打头），但是从现在的sym文件的内容来看，似乎这里是十六进制下的值？

**Comment by a1exwang** [comment]
1. 我没有使用bss段, 因为最开始文档中写着文件头bss这个field不用. 所以我就把bss合并到data段中了
   2, 3 我写错了

**Comment by JianxinMa** [comment]
你是指我之前那个debugger文档吗？我模糊记得我好想写过bss，但当时的意思是不需要存bss段的变量的值（因为都是0），而不是不用bss段（可能是我表述不好...）

另外，从这个片段看，似乎你的输出还是认为arr的地址是在bss段的。

```
arr data +13010
...
.bss 0x13010
```

**Comment by JianxinMa** [comment]
哦，还有，函数开始地址那个，是“>“，不是”<"，也顺手改下吧

**Comment by a1exwang** [comment]
-_-!
