### ISSUE TITLE
关于text段地址和entrypoint

### ISSUE THREAD

**Issue by JianxinMa** [a1exwang/alex2v9#6]
1. 请问你是假定
      header段占据地址0x00~0x10，而text等其他段占据0x10后的部分吗？还是
      无视header，让text段等从0x0开始？
2. v9的header里的entry指的是cpu启动后应该设置的第一个pc值，你的entry值也是这个含义吗？

**Comment by a1exwang** [comment]
由于elf中还有其他有用的段, 比如rodata, 而且位置关系是这样的:
+0x11000 .rodata1
+0x110d5 .rodata2
+0x12000 .text
+0x13000 .data
+0x13d00 .bss
我得做法是这样的:
1. text段和text段以前的段一并合并到v9的text段, 由于elf的第一个段偏移量一定大于0x10(有elf头), 所以可以从0x10开始补0, 一直补到第一个段开始的地址(0x11000), 都算作v9的text段, 也就是说0x10~0x12xxx(0x12xxx是elf中text段结束地址)都是v9的text段,
2. data段和data段之后的段合并成为v9的data段.
3. 对于bss段
由于参考了陈渝老师的文档的这个部分:

```
struct { 
 uint magic //0xC0DEF00D 文件的magic number 
 uint bss　 //在v9-cpu执行时没有用到(这里说bss没有用到, 所以我也不使用这个字段)
 uint entry //程序的执行入口地址
 uint flags;//程序的数据段起始地址 
} hdr;
```

我把bss段放到了data段中, 并且补0,
所以v9的text段范围是0x12000~(0x13000+sizeof(.bss))

**Comment by a1exwang** [comment]
entry的含义是这样的

**Comment by a1exwang** [comment]
[alexv9.zip](https://github.com/a1exwang/alex2v9/files/305926/alexv9.zip)

**Comment by JianxinMa** [comment]
（关于bss，它说没有用到是指bss的地址给不给都不影响运行（内存已初始化为全0了），而不是没用bss段——不过这不是什么重要的细节。）

“所以v9的text段范围是0x12000~(0x13000+sizeof(.bss))”这句话，你是指data段吗，打错了？

然而还是有一堆R0的warning...
